### ISSUE TITLE
WARN thrown and spammed into console

### ISSUE THREAD

**Issue by Skizzles** [SchnTgaiSpock/SlimeHUD#3]
## Description (Required)
This warn is thrown once and then continues to be spammed until the server restarts and it occurs again

## Steps to reproduce the Issue (Required)
[00:02:32] [Server thread/WARN]: [SlimeHUD] Task #220297722 for SlimeHUD v1.2.2 generated an exception
java.lang.ArithmeticException: / by zero
	at io.github.schntgaispock.slimehud.util.HudBuilder.formatProgressBar(HudBuilder.java:99) ~[SlimeHUD.v1.2.2.jar:?]
	at io.github.schntgaispock.slimehud.waila.HudController.processMachine(HudController.java:105) ~[SlimeHUD.v1.2.2.jar:?]
	at io.github.schntgaispock.slimehud.waila.HudController.processRequest(HudController.java:206) ~[SlimeHUD.v1.2.2.jar:?]
	at io.github.schntgaispock.slimehud.waila.PlayerWAILA.getFacing(PlayerWAILA.java:67) ~[SlimeHUD.v1.2.2.jar:?]
	at io.github.schntgaispock.slimehud.waila.PlayerWAILA.run(PlayerWAILA.java:82) ~[SlimeHUD.v1.2.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1752]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1752]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1518) ~[purpur-1.19.2.jar:git-Purpur-1752]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.2.jar:git-Purpur-1752]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1442) ~[purpur-1.19.2.jar:git-Purpur-1752]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[purpur-1.19.2.jar:git-Purpur-1752]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1752]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

## Expected behavior (Required)
An error not being sent.

## Server Log / Error Report
N/A

## Environment (Required)

- Minecraft Version: 1.19.2
- Slimefun Version: 1027 dev
- Plugin Version: 1.2.2

**Comment by SchnTgaiSpock** [comment]
fixed in version 1.2.3 and up
